'use client'

import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { useState, useEffect } from 'react'

// const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = extendTheme({
  styles: {
    global: {
      body: {
        bg: '#f8f8f8',
      },
    },
  },
});

export default function RootLayout({ children }) {
  const [isMockingReady, setIsMockingReady] = useState(false)

  // useEffect(() => {
  //   const enableMocking = async () => {
  //     if (typeof window !== 'undefined') {
  //       if (process.env.NODE_ENV === 'development') {
  //         const { worker } = await import('../mocks/browser');
  //         await worker.start({
  //           onUnhandledRequest: 'bypass',
  //         })
  //       }
  //     }
  //   }
  //   enableMocking().then(() => setIsMockingReady(true));
    
  // }, [])

  return (
    <html lang="zh-TW">
      <body>
        {/* {isMockingReady && */}
        <ChakraProvider theme={theme}>
          {children}
        </ChakraProvider>
        {/* } */}
      </body>
    </html>
  );
}
