'use client'

import { ChakraProvider, extendTheme } from '@chakra-ui/react';

// const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = extendTheme({
  styles: {
    global: {
      body: {
        bg: '#f8f8f8',
      },
    },
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="zh-TW">
      <body>
        <ChakraProvider theme={theme}>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
